# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name': 'Url', 'verbose_name_plural': 'Urls'},
        ),
    ]
